var a=20;
var b=4;
var c=12;
var d=a+b-c;
var e=a*b/c;
console.log(e);
console.log(d);
var x=7.82456;
var y=x.toPrecision(4);
var z=x.toPrecision();
console.log(y);
console.log(z);
var a=123;
b=a.toString();
console.log(b+12);
